// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUjj5qrbpsKFYTfeveqB6jM3bOEQO_DIU',
    appId: '1:827610982642:web:188f19349f25367c73486b',
    messagingSenderId: '827610982642',
    projectId: 'eproject-1b347',
    authDomain: 'eproject-1b347.firebaseapp.com',
    storageBucket: 'eproject-1b347.appspot.com',
    measurementId: 'G-B3MQB7D0EP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMyKBohrGAZqtcCGx1BLLKGb4tcat46lY',
    appId: '1:827610982642:android:ca75160f94e960fb73486b',
    messagingSenderId: '827610982642',
    projectId: 'eproject-1b347',
    storageBucket: 'eproject-1b347.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVbu0XRgTHlk74UgSFMLwXugqpNI6M6l4',
    appId: '1:827610982642:ios:bc44c298bbfa0bca73486b',
    messagingSenderId: '827610982642',
    projectId: 'eproject-1b347',
    storageBucket: 'eproject-1b347.appspot.com',
    iosBundleId: 'com.example.eproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVbu0XRgTHlk74UgSFMLwXugqpNI6M6l4',
    appId: '1:827610982642:ios:9206ea73d39ee3d773486b',
    messagingSenderId: '827610982642',
    projectId: 'eproject-1b347',
    storageBucket: 'eproject-1b347.appspot.com',
    iosBundleId: 'com.example.eproject.RunnerTests',
  );
}
